version: "3"
services:
    app:
        image: fast4info:0.1.0
        env_file:
            - production.env
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: 150m
                reservations:
                    cpus: '0.01'
                    memory: 50m
    mongo:
        image: mongo
        deploy:
            resources:
                limits:
                    cpus: '0.05'
                    memory: 250m
                reservations:
                    cpus: '0.01'
                    memory: 100m